import './bootstrap';
import { createApp } from 'vue';
import router from './router/router';  
import store from './store';  
import App from './App.vue';
import LoadScript from "vue-plugin-load-script";
import VueSweetalert2 from 'vue-sweetalert2';
import 'sweetalert2/dist/sweetalert2.min.css';
const app = createApp(App);
app.use(LoadScript);
app.use(VueSweetalert2); 
app.use(store); 
app.use(router); 
app.mount('body');
